### PR TITLE
Adds test coverage for alpine linux

### PR DESCRIPTION
**Pull request by paulirish**
_(redoing [this PR](https://github.com/AkshayIyer12/chrome-launcher/pull/1) against the real upstream)_

text from @danbopes:

-----

I've gone ahead and added some alpine test coverage using travis-ci and docker to build an alpine image and test the run in there. It may need some tweaks/changes (chromium appears to be in /usr/lib/chrome, but it may not be functionality correctly), but this should be a good start to determine if this is working correctly.

See the following docker test:

See a sample build output of it failing [here](https://travis-ci.org/danbopes/chrome-launcher/jobs/299823717).

### CODE REVIEW

**Comment by danbopes** [comment]
The fork was ultimately for him to integrate and continue testing in his environment, to ultimately merge into your repo.

**Comment by danbopes** [comment]
@googlebot ping CLA complete

**Comment by samccone** [comment]
Spent some time digging into this one. Once I saw what tests were failing it became somewhat obvious that there was an issue with any of the tests that actually launch chrome:
```
  ChromeLauncher:error connect ECONNREFUSED 127.0.0.1:33563 +0ms
  ChromeLauncher:error Logging contents of /tmp/lighthouse.XocAHcn/chrome-err.log +2ms
  ChromeLauncher:error [131:131:0401/180724.977072:ERROR:browser_main_loop.cc(279)] Gtk: cannot open display: :99.0
  ChromeLauncher:error  +0ms
```

But this was not enough to identify the root issue. By connecting to the docker image and overwriting the entry point to `/bin/bash` I was able to run the tests and then dump out the error log from chrome:

```
[100:100:0401/181553.727881:FATAL:zygote_host_impl_linux.cc(107)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.m
```

So issue #25 strikes again!

**Comment by samccone** [comment]
After turning the flag off, and giving chrome enough time to launch we are greeted by another fun error message

```
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
[316:316:0401/182733.195220:FATAL:zygote_host_impl_linux.cc(182)] Check failed: ReceiveFixedMessage(fds[0], kZygoteBootMessage, sizeof(kZygoteBootMessage), &boot_pid).
```

This seems to be due to the fact that I did not run the container as --privileged 
https://github.com/jessfraz/dockerfiles/issues/65

Once I added that flag to my docker command I was presented with this remaining error
`[67:67:0401/183329.379889:ERROR:browser_main_loop.cc(279)] Gtk: cannot open display: :99.0`

Which looks to be due to the fact that I am running the docker image on my mac and am not correctly forwarding my X11 server into my docker image execution
https://www.thegeekstuff.com/2010/06/xhost-cannot-open-display/

**Comment by samccone** [comment]
Alright spent a few more hours on this, still unable to run this locally, and it is running partially on travis

https://github.com/GoogleChrome/chrome-launcher/pull/101

If any feels like picking this back up, please ping this PR and you can have at it.

Thanks

**Pull request closed without merging**
