### PR TITLE
 docs(chrome-flags-for-tools): add link to overview of features

### PR DESCRIPTION
**Pull request by Niek**
Add a link to a continuously updated feature overview.

### CODE REVIEW

**Comment by paulirish** [comment]
this is very cool. :D

**Comment by connorjclark** [comment]
I'd like to merge this, but first I wanted to verify how recent the flags are, but I don't have a quick way to do that. Would you be able to add the chrome revision / date / something on the page, to help users quickly understand "yup, this is up to date!"

**Comment by Niek** [comment]
Good point @connorjclark! I have added a footer with the build date now at https://niek.github.io/chrome-features/ (it's updated daily).

**Review by connorjclark — APPROVED** [review]
Thanks!

**Pull request merged**
