### PR TITLE
Add additional chrome flags

### PR DESCRIPTION
**Pull request by paulirish**
extra descriptions of these at https://github.com/GoogleChrome/chrome-launcher/blob/master/docs/chrome-flags-for-tools.md

### feels good
- `disable-component-update`.. this is huge, as I don't believe `disable-background-networking` was toggling this off.
- `disable-client-side-phishing-detection`. probably not a huge deal, but why not.
- `disable-ipc-flooding-protection`. Been default in pptr since 2018. https://github.com/puppeteer/puppeteer/commit/2a88690582cf01c8a338a972b352c34738e6bfdf seems good
- `password-store=basic` and `use-mock-keychain`. default in chromedriver/pptr.  see links in the markdown.

### not sure....

- `enable-automation`. most of the [benefits](https://github.com/GoogleChrome/chrome-launcher/blob/master/docs/chrome-flags-for-tools.md#test--debugging-flags) are great, but the added infobar caused some problems for webplatformtests: https://github.com/web-platform-tests/wpt/pull/6348. thoughts?

closes #23 (so old. made redundant, finally)

### CODE REVIEW

**Review by brendankenny — APPROVED** [review]
> * `enable-automation`. most of the [benefits](https://github.com/GoogleChrome/chrome-launcher/blob/master/docs/chrome-flags-for-tools.md#test--debugging-flags) are great, but the added infobar caused some problems for webplatformtests: [web-platform-tests/wpt#6348](https://github.com/web-platform-tests/wpt/pull/6348). thoughts?

Seems like it could be ok, but do we have any tests sensitive enough to window size/positioning that we may get errors like they saw in https://groups.google.com/a/chromium.org/g/platform-predictability/c/k1I70ez7suM/m/1iskWQeKAgAJ ?

**Comment by brendankenny** [comment]
> > * `enable-automation`. most of the [benefits](https://github.com/GoogleChrome/chrome-launcher/blob/master/docs/chrome-flags-for-tools.md#test--debugging-flags) are great, but the added infobar caused some problems for webplatformtests: [web-platform-tests/wpt#6348](https://github.com/web-platform-tests/wpt/pull/6348). thoughts?
> 
> Seems like it could be ok, but do we have any tests sensitive enough to window size/positioning that we may get errors like they saw in https://groups.google.com/a/chromium.org/g/platform-predictability/c/k1I70ez7suM/m/1iskWQeKAgAJ ?

running Lighthouse's `yarn smoke` with this branch of chrome-launcher had no errors, at least

**Comment by brendankenny** [comment]
element rects and the full-page-screenshot also look properly aligned, so seems ok to me

**Comment by paulirish** [comment]
> > * `enable-automation`. most of the [benefits](https://github.com/GoogleChrome/chrome-launcher/blob/master/docs/chrome-flags-for-tools.md#test--debugging-flags) are great, but the added infobar caused some problems for webplatformtests: [web-platform-tests/wpt#6348](https://github.com/web-platform-tests/wpt/pull/6348). thoughts?
> 
> Seems like it could be ok, but do we have any tests sensitive enough to window size/positioning that we may get errors like they saw in [groups.google.com/a/chromium.org/g/platform-predictability/c/k1I70ez7suM/m/1iskWQeKAgAJ](https://groups.google.com/a/chromium.org/g/platform-predictability/c/k1I70ez7suM/m/1iskWQeKAgAJ) ?

on second thought i don't think we want this.  i'd take it if it didnt add its own infobar.

but i just had a bunch that the infobar mucks with the screenshots and.. indeed it does.

image

that issue: https://github.com/GoogleChrome/lighthouse/issues/4451

**Pull request merged**
